### ISSUE TITLE
[ERROR] java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by flora7883** [SujungVillage/SujungVillage-User-Android#63]
# 📝 Description
> ### API연결 중 발생한 오류
같은 오류 발생했던 사람 있으면 해결방법 공유해주세요..

오류 메시지
2022-08-03 00:39:20.315 28660-28660/kr.co.sujungvillage E/AndroidRuntime: FATAL EXCEPTION: main
    Process: kr.co.sujungvillage, PID: 28660
    java.lang.ExceptionInInitializerError
        at kr.co.sujungvillage.CommWriteActivity.onCreate$lambda-1(CommWriteActivity.kt:39)
        at kr.co.sujungvillage.CommWriteActivity.$r8$lambda$4Lbab-ffmG0sEd70mO9ybSB_Yog(Unknown Source:0)
        at kr.co.sujungvillage.CommWriteActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1332)
        at okhttp3.HttpUrl.get(HttpUrl.java:917)
        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:506)
        at kr.co.sujungvillage.retrofit.RetrofitBuilder.<clinit>(RetrofitBuilder.kt:19)
        at kr.co.sujungvillage.CommWriteActivity.onCreate$lambda-1(CommWriteActivity.kt:39) 
        at kr.co.sujungvillage.CommWriteActivity.$r8$lambda$4Lbab-ffmG0sEd70mO9ybSB_Yog(Unknown Source:0) 
        at kr.co.sujungvillage.CommWriteActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2) 
        at android.view.View.performClick(View.java:7448) 
        at android.view.View.performClickInternal(View.java:7425) 
        at android.view.View.access$3600(View.java:810) 
        at android.view.View$PerformClick.run(View.java:28305) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 

# 📂 Location
- **CommWriteActivity** 이 부분에서 오류 발생
- `RetrofitBuilder.commWriteApi.CommWrite(userId,commWriteInfo).enqueue(object: Callback<CommWriteResultDTO>{
                override fun onResponse(call: Call<CommWriteResultDTO>, response: Response<CommWriteResultDTO>) {
                    Toast.makeText(this@CommWriteActivity,"성공: ${title}, ${content}",Toast.LENGTH_LONG).show()
                    Log.d("COMMWRITE", response.body().toString())
                }
                override fun onFailure(call: Call<CommWriteResultDTO>, t: Throwable) {
                    Toast.makeText(this@CommWriteActivity,"실패: ${title}, ${content}",Toast.LENGTH_LONG).show()
                    Log.d("COMMWRITE","커뮤니티 글 쓰기 실패")
                }
            })`
RetrofitBuilder.commWriteApi.CommWrite(userId,commWriteInfo).enqueue(object: Callback<CommWriteResultDTO>{
                override fun onResponse(call: Call<CommWriteResultDTO>, response: Response<CommWriteResultDTO>) {
                    Toast.makeText(this@CommWriteActivity,"성공: ${title}, ${content}",Toast.LENGTH_LONG).show()
                    Log.d("COMMWRITE", response.body().toString())
                }
                override fun onFailure(call: Call<CommWriteResultDTO>, t: Throwable) {
                    Toast.makeText(this@CommWriteActivity,"실패: ${title}, ${content}",Toast.LENGTH_LONG).show()
                    Log.d("COMMWRITE","커뮤니티 글 쓰기 실패")
                }
            })
- **CommWriteService.kt**
-interface CommWriteService {
    //커뮤니티 글 쓰기
// 외박 신청
    @POST("/api/common/community/writePost")
    fun CommWrite(
        @Header("user_id") userId: String?,
        @Body commWriteInfo: CommWriteDTO,
    ): Call<CommWriteResultDTO>
}

- **CommWrite.kt**
data class CommWriteDTO(
    @SerializedName("title")
    val title: String,
    @SerializedName("content")
    val content: String,
): Serializable {}
data class CommWriteResultDTO(
    @SerializedName("id")
    val id:Long,
    @SerializedName("writer")
    val writer:CommWriteUser,
    @SerializedName("title")
    val title:String,
    @SerializedName("content")
    val content:String,
    @SerializedName("reg_date")
    val reg_date:String,
    @SerializedName("mod_date")
    val mod_date:String
):Serializable {}
data class CommWriteUser(
    @SerializedName("id")
    val id:String,
    @SerializedName("name")
    val name:String,
    @SerializedName("phoneNumber")
    val phoneNumber:String,
    @SerializedName("domitory")
    val domitory:CommWriterDormitory,
    @SerializedName("detailAddress")
    val detailAddress:String,
    @SerializedName("authority")
    val authority:String
):Serializable {}
data class CommWriterDormitory(
    @SerializedName("domitoryName")
    val domitoryName:String,
    @SerializedName("address")
    val address:String
):Serializable {}

 - **RetrotifBuilder**
 commWriteApi=retrofit.create(CommWriteService::class.java)

**Comment by b1urrrr** [comment]
Call이나 Callback 뒤에 <> 이 괄호 안에 Output 타입 적어줘야할 것 같아! 
혹시 local.properties에 base_url은 어떻게 추가했었어?

**Comment by flora7883** [comment]
15.165.188.210:8080/ 이렇게 적었어!

**Comment by b1urrrr** [comment]
> 15.165.188.210:8080/ 이렇게 적었어!

http://15.165.188.210:8080/ 이걸로 한번 수정해볼래? (실수로 이슈 닫았다가 다시 열었어 😅 )

**Comment by flora7883** [comment]
> > 15.165.188.210:8080/ 이렇게 적었어!
> 
> http://15.165.188.210:8080/ 이걸로 한번 수정해볼래? (실수로 이슈 닫았다가 다시 열었어 😅 )

지금 노트북 꺼서 내일 일어나서 해볼게!

**Comment by flora7883** [comment]
> Call이나 Callback 뒤에 <> 이 괄호 안에 Output 타입 적어줘야할 것 같아! 혹시 local.properties에 base_url은 어떻게 추가했었어?

코드 잘못 올려놔서 다시 수정했어! CommWriteResultDTO이거 적어놨어! base url 바꾸니까 저 오류는 안뜨는데 onFailure로 넘어가네

**Comment by b1urrrr** [comment]
> > Call이나 Callback 뒤에 <> 이 괄호 안에 Output 타입 적어줘야할 것 같아! 혹시 local.properties에 base_url은 어떻게 추가했었어?
> 
> 
> 
> 코드 잘못 올려놔서 다시 수정했어! CommWriteResultDTO이거 적어놨어! base url 바꾸니까 저 오류는 안뜨는데 onFailure로 넘어가네

서버가 꺼져있을 수도...!

**Comment by b1urrrr** [comment]
아 그리고 @post 이거 @POST 이렇게 대문자로 써야할 수도 있을 것 같아!

**Comment by flora7883** [comment]
t.message.toString()으로 오류 메세지 띄워봤더니 아래 메세지가 뜸.
CLEARTEXT communication to xx.xxx.xxx not permitted by network security policy
-> 해결 방법
manifest에서       application에   android:usesCleartextTraffic="true"를 추가해주면 됨
