### ISSUE TITLE
[ERROR] 점호 주소 반환 Null Pointer 오류

### ISSUE THREAD

**Issue by b1urrrr** [SujungVillage/SujungVillage-User-Android#94]
# 📝 Description
> ### 점호(RollcallActivity)에서 위치 새로고침 버튼 클릭 시 NullPointer 오류가 발생하는 경우가 많이 발생합니다. 같이 머리를 맞대고 해결해봅시다...🥲 

# 📂 Location
- **RollcallActivity.kt** 200 번째 줄

# 👩‍💻 오류 코드
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: kr.co.sujungvillage, PID: 7459
    java.lang.NullPointerException
        at kr.co.sujungvillage.RollcallActivity.getLatLng(RollcallActivity.kt:200)
        at kr.co.sujungvillage.RollcallActivity.getCurrentLoc(RollcallActivity.kt:150)
        at kr.co.sujungvillage.RollcallActivity.onCreate$lambda-3(RollcallActivity.kt:63)
        at kr.co.sujungvillage.RollcallActivity.$r8$lambda$aol-sC1MqMH8pmsN8VPa3O-co0Y(Unknown Source:0)
        at kr.co.sujungvillage.RollcallActivity$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by flora7883** [comment]
아직 해결 안된거야?
나도 고민 해볼게!

**Comment by b1urrrr** [comment]
민경이가 예외처리 해놓은 상태!
